### ISSUE TITLE
What is the number in the middle?

### ISSUE THREAD

**Issue by Nagidal** [votacom/octalsuntime#33]
Readme does not explain what the three-digit number in the middle says.

**Comment by votacom** [comment]
Would you like the README to be as detailed as [the F-Droid description](https://github.com/votacom/octalsuntime/blob/master/fastlane/metadata/android/en-US/full_description.txt)?

> In addition, the octal hour and minute is also shown digitally as a three-digit octal number in the center.

**Comment by Nagidal** [comment]
Yes, I think that would have been helpful. Or at least add that quoted sentence there.

**Comment by Nagidal** [comment]
Also, what maybe a separate issue, why did you choose the format `HMM` rather than something more intuitively understandable, e.g. `H:MM`. I think I would have figured that out. Although, even for the 24h format we sometimes use the military format `HHMM` (e.g. at `0800` hours), so I guess you could argue that the `HMM` for the octal is a bit more terse and in that same spirit.

**Comment by votacom** [comment]
We chose the representation as a single number to make arithmetics easy. It is compatible with other octal time systems, e.g. one with 64 hours per day.

ToDo: make README As detailed as the F-Droid long description.

**Comment by votacom** [comment]
The README has been adapted. Closing this issue.

**Comment by ghost** [comment]
@Nagidal I don't think it is of format HMM as then MM could not be above 64.

I honestly don't understand it either. I think we need to study octal system more. :-) 

https://en.m.wikipedia.org/wiki/Octal
